use_frameworks!

target 'Delirium_Example' do
  pod 'Delirium', :path => '../'

  target 'Delirium_Tests' do
    inherit! :search_paths

    # The test frameworks
    pod 'Quick',            '~> 0.8'
    pod 'Nimble',           '~> 3.0'
    pod 'Nimble-Snapshots', '~> 4.1'
  end
end
